name: food_app_ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Updated version to match firebase_storage
  cloud_firestore: ^5.4.4  # Ensure compatibility
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4  # No change here
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.0.9
  flutter_paypal: ^0.0.3
  http: ^0.13.4
  appcheck: ^1.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
